# Uncomment this line to define a global platform for your project
platform :osx, '10.10'

def shared_pods
  pod 'libxlsxwriter', '~> 0.3.1'

end

target 'FauxPasReportConverter'  do
  shared_pods
end

target 'FauxPasReportConverterTests'  do
  shared_pods
end

target 'FauxPasReportConverterUITests'  do
  shared_pods
end
